### ISSUE TITLE
Not working for email type fields.

### ISSUE THREAD

**Issue by vikrambabu2** [TheSharpieOne/angular-input-match#20] opened 2015-03-12 13:33 UTC
The directive is not working for email type fields. I have already risen an issue for this. The issue number is #19. But unfortunately, the issue is closed with any solution. Can you look into this issue #19 ?

**Comment by TheSharpieOne** [comment] 2015-03-12 14:56
This is a duplicate of #19, please use the original issue.

**Closed by TheSharpieOne** 2015-03-12 14:56 UTC
Labels: duplicate
